version: 2.1

jobs:
  smoke_test:
      docker:
        - image: amazon/aws-cli
      steps:
        - run: yum -y install tar gzip
        - run: yum  install nodejs 
           

workflows:
  my_workflow:
    jobs:
      - smoke_test
         