version: 2.1

jobs:
  smoke_test:
      docker:
        - image: alpine:latest
      steps:
        - run: apk add --update curl
        - run: yum install -y tar
           

workflows:
  my_workflow:
    jobs:
      - smoke_test
         