version: 2.1

jobs:
  configure_infrastructures:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["26:2f:64:21:06:3d:17:e9:59:cc:f2:6f:52:62:50:80"] # You can get this ID in the section where you registered the SSH Key
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible # install the dependencies needed for your playbook
      - run:
          name: Configure server
          command: |
            ansible-playbook .circleci/main.yml 

workflows:
  my_workflow:
    jobs:
      - configure_infrastructures