version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
              aws s3 ls
workflows:
  my_workflow:
    jobs:
      - create_infrastructure