version: 2.1

jobs:
  my_jobs:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: return 1
      - run: 
          name: on error
          command: echo "failed"
          when: on_fail

workflows:
  my_workflow:
    jobs:
      - my_jobs